dist: xenial

language: cpp
compiler:
  - gcc
  - clang

install:
  # https://riptutorial.com/cmake/example/4723/configure-travis-ci-with-newest-cmake
  # -- Update CMake to 3.13.4 --
  - DEPS_DIR="${TRAVIS_BUILD_DIR}/deps"
  - mkdir ${DEPS_DIR} && cd ${DEPS_DIR}
  - travis_retry wget --no-check-certificate https://cmake.org/files/v3.13/cmake-3.13.4-Linux-x86_64.tar.gz
  - echo "8b743ed020503c8e66952e73b92630c2 *cmake-3.13.4-Linux-x86_64.tar.gz" > cmake_md5.txt
  - md5sum -c cmake_md5.txt
  - tar -xvf cmake-3.13.4-Linux-x86_64.tar.gz > /dev/null
  - mv cmake-3.13.4-Linux-x86_64 cmake-install
  - PATH=${DEPS_DIR}/cmake-install:${DEPS_DIR}/cmake-install/bin:$PATH
  - cd ${TRAVIS_BUILD_DIR}

script:
  # -- Run CMake --
  - mkdir build
  - cd build
  - cmake ../ -DWARNINGS_PEDANTIC=1 -DWARNINGS_AS_ERRORS=1 -DCMAKE_BUILD_TYPE=Debug -DBUILD_TESTS=1
  # -- Compile --
  - $CXX --version
  - make -j 4 -k
  - make CTEST_OUTPUT_ON_FAILURE=1 test
