dist: xenial
cache: packages

language: cpp
compiler:
  - gcc
  - clang

addons:
  apt:
    sources:
    - sourceline: 'ppa:chris-lea/libsodium'
    packages:
    - libsodium-dev

script:
  # -- Run CMake --
  - mkdir build
  - cd build
  - cmake ../ -DENABLE_ENCRYPTION=1 -DWARNINGS_PEDANTIC=1 -DWARNINGS_AS_ERRORS=1 -DCMAKE_BUILD_TYPE=Debug -DBUILD_TESTS=1
  # -- Compile --
  - $CXX --version
  - make -j 4 -k
  - make CTEST_OUTPUT_ON_FAILURE=1 test
