dist: xenial

language: cpp
compiler:
  - gcc
  - clang

git:
  depth: 1

install:
  # Update CMake to minimum required of 3.13
  # Politely borrowed from https://github.com/ldionne/hana/blob/master/.travis.yml
  - |
    if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then
      CMAKE_URL="https://cmake.org/files/v3.13/cmake-3.13.4-Linux-x86_64.tar.gz"
      mkdir cmake && travis_retry wget --no-check-certificate --quiet -O - ${CMAKE_URL} | tar --strip-components=1 -xz -C cmake
      export PATH=${DEPS_DIR}/cmake/bin:${PATH}
    else
      brew install cmake || brew upgrade cmake
    fi
  - cmake --version
  # Run CMake
  - mkdir build
  - cd build
  - cmake ../ -DWARNINGS_PEDANTIC=1 -DWARNINGS_AS_ERRORS=1 -DCMAKE_BUILD_TYPE=Debug
  - cd ..

script:
  - $CXX --version
  - cd build
  - make -j 4 -k
