version: '0.1.{build}'
image: Visual Studio 2017

pull_requests:
  do_not_increment_build_number: true

configuration:
- Debug
- RelWithDebInfo

clone_depth: 1

before_build:
  - mkdir build
  - cd build
  - cmake -G "Visual Studio 15 2017 Win64" ..\ -DWARNINGS_PEDANTIC=1 -DWARNINGS_AS_ERRORS=1 -DCMAKE_BUILD_TYPE=Debug -DBUILD_TESTS=1

build:
  verbosity: minimal
  project: $(APPVEYOR_BUILD_FOLDER)\build\$(APPVEYOR_PROJECT_NAME).sln

test_script:
  - 'echo %APPVEYOR_BUILD_FOLDER%\build\tests\%CONFIGURATION%\tests.exe'
  - '%APPVEYOR_BUILD_FOLDER%\build\tests\%CONFIGURATION%\tests.exe'
